language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t mparaskakis/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mparaskakis/react-test npm test

after_success:
  - docker build -t mparaskakis/multi-client ./client
  - docker build -t mparaskakis/multi-server ./server
  - docker build -t mparaskakis/multi-worker ./worker
  - docker build -t mparaskakis/multi-nginx ./nginx

  # Log in to the docker CLI through Travis
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take images and push them to docker hub
  - docker push mparaskakis/multi-client
  - docker push mparaskakis/multi-nginx
  - docker push mparaskakis/multi-server
  - docker push mparaskakis/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: MultiDocker-env
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-530114946190
  bucket_path: MultiDocker-env
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
